name: App CI Build

on:
  push:
    tags:
      - 'v*' 

permissions:
  contents: read
  actions: read
  packages: write

jobs:
  trigger-internal-build:
    uses: infras/workflow-templates/.gitea/workflows/docker-template.yml@9d34c16fceb781900c5c079ad06bccf499fbfb2e
    with:
      image_name: 'simple-http-server'
      image_owner: thistine
      image_tag: ${{ gitea.ref_name }} 