name: App CI Build

on:
  push:
    tags:
      - 'v*' 

permissions:
  contents: read
  actions: read
  packages: write

jobs:
  trigger-internal-build:
    uses: infras/workflow-templates/.gitea/workflows/docker-template.yml@4e34f8467cfab0bf56b4155285a5612a3c9ec6d3
    with:
      image_name: 'simple-http-server'
      image_tag: ${{ gitea.ref_name }}
    secrets:
      REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
      REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }} 