name: App CI Build

on:
  push:
    tags:
      - 'v*' 

permissions:
  contents: read
  actions: read

jobs:
  trigger-internal-build:
    uses: infras/workflow-templates/.gitea/workflows/docker-template.yml@c136ee94507f337048f0257465d52f5a270e308a
    with:
      image_name: 'simple-http-server'
      image_tag: ${{ gitea.ref_name }} 